export const FETCH_EXERCISES = 'FETCH_EXERCISES';
export const FETCH_EXERCISES_BY_BODY_PART = 'FETCH_EXERCISES_BY_BODY_PART';
export const FETCH_EXERCISES_BY_TARGET = 'FETCH_EXERCISES_BY_TARGET';
export const FETCH_EXERCISES_BY_EQUIPMENT = 'FETCH_EXERCISES_BY_EQUIPMENT';
export const FETCH_EXERCISE_BY_EXERCISE_ID = 'FETCH_EXERCISE_BY_EXERCISE_ID';
export const FILTER_SEARCHED_EXERCISES = 'FILTER_SEARCHED_EXERCISES'; 